# Практическое задание

В этом практическом задании мы поработаем с алгоритмом линейной регрессии и нормализацией признаков. Для начала загрузите данные из файла `data.csv`, который содержит 100 признаков f1, f2, ..., f100 и целевую переменную target. Для загрузки данных используете функцию `read_csv` из библиотеки `pandas`. Выделите матрицу признаков и целевую переменную из загруженных данных.

### *РЕШЕНИЕ*

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("data.csv")
df.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f92,f93,f94,f95,f96,f97,f98,f99,f100,target
0,-1.979019,0.392456,1.195177,0.209349,-1.209435,0.868798,0.384209,-0.426571,-0.977939,-1.419877,...,-1.587188,-0.612423,-0.281845,-0.625773,-0.907327,-0.800223,0.065892,0.271684,-0.201420,-45.587910
1,0.613518,0.051946,0.238789,-0.071601,-0.080717,1.727543,-0.483886,0.635172,0.038003,1.573987,...,0.059630,0.120031,0.399223,0.494030,0.197600,0.652323,0.916328,-1.556582,-0.370614,137.329473
2,0.444198,-0.535317,0.664927,-0.327017,1.935154,-1.776012,0.207803,0.126178,0.252569,0.889037,...,0.195482,1.384532,0.522251,-0.127655,-0.403076,-0.111509,-0.183150,0.977816,-1.171654,141.355900
3,-1.485186,-0.101987,0.817982,-0.846498,-0.660834,-0.073107,-0.247340,-0.775607,1.015937,-1.075737,...,0.753417,-0.403380,0.087974,-1.525572,2.404838,0.011863,0.994299,-2.152914,-0.213593,-65.882640
4,0.276582,-0.208468,0.185689,0.508608,-1.527168,-1.373403,-0.481766,-2.854627,1.868818,-1.179460,...,-0.985540,0.419706,-0.610858,0.209534,-0.538048,0.164295,-0.984655,-0.598438,-0.887770,-333.409221

Далее, разделите загруженный датасет на тренировочную и тестовую выборку. Для этого используйте функцию `train_test_split` из модуля `sklearn.model_selection` с параметрами `random_state=42` и `test_size=0.33`. Обучите линейную регрессию на тренировочных данных и оцените среднеквадратическую ошибку на тестовых данных. Один из вариантов линейной регрессии в `scikit-learn` представлен классом `Ridge` из `sklearn.linear_model`.
Используйте параметр `random_state=42` в конструкторе класса при создании его экземпляра. Оценку среднеквадратичной ошибки проведите с помощью функции `mean_squared_error` из модуля `sklearn.metrics`. В качестве ответа `answer1` приведите это значение округлённое с точностью до двух знаков.

### *РЕШЕНИЕ*

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Ridge

In [3]:
train, test = train_test_split(df, random_state=42, test_size=0.33)

In [4]:
model = Ridge(random_state=42)

In [5]:
model.fit(train.drop(columns=['target']), train["target"])

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=42, solver='auto', tol=0.001)

In [6]:
data = model.predict(test.drop(columns=['target']))

In [7]:
answer1 = round(mean_squared_error(data, test["target"]), 2)
answer1

4921.83

In [8]:
train.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f92,f93,f94,f95,f96,f97,f98,f99,f100,target
9,1.392039,-0.664651,-1.422230,-1.941859,0.809265,-0.491562,-0.528947,0.856976,-0.516847,0.084094,...,0.958816,0.619033,-0.443263,-1.353755,1.212129,-0.432295,0.880066,0.357661,-1.499181,-27.045030
33,-0.182161,0.091125,0.632216,0.604052,0.998218,-0.333486,0.338976,0.818766,0.879014,-0.122436,...,-0.480574,-0.946491,0.281192,-0.504423,-1.932065,0.627680,2.206469,1.600098,-0.761941,-291.415251
62,0.072681,-0.617642,0.893698,-0.409687,-1.880010,-0.139397,-0.755792,0.572390,-1.909356,0.443002,...,1.649481,1.318302,-1.731201,-2.906988,-0.283139,-0.707626,-0.372319,-1.466785,0.313184,-14.484626
25,0.522521,-0.216419,-0.335516,1.251947,-0.778309,-0.176134,0.001804,0.976507,-1.688034,1.054621,...,2.305637,-0.600748,-0.455342,0.686774,-0.701957,0.268413,1.612868,1.896123,2.054092,18.230694
119,-1.179369,0.751099,-0.548200,-1.689183,0.028458,-0.262660,0.548320,-1.406815,0.960305,0.388312,...,1.669070,0.462484,0.887504,2.184097,0.218534,0.537630,1.643378,0.506241,0.186416,-36.199008

Далее вам предлагается стандартизовать данные используя `StandardScaler` из `sklearn.preprocessing`. По своей сути операция стандартизации в данном случае представляет из себя вычитание среднего из матрицы признаков и деление на среднеквадратическое отклонение. 

<font color  = "red">Важно:</font> Сначала следует разбить выборку на тренировочную и тестовую и лишь потом стандартизировать их по отдельности. Помните, что к тренировочной выборке мы должны применять метод `fit_transform()`, а к тестовой только `transform()`. Как изменилось качество на тестовых данных? В `answer2` запишите значение среднеквадратической ошибки, округлённое с точностью до двух знаков после запятой.

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
train_scalar = StandardScaler()
train_scaled = train_scalar.fit_transform(train.drop(columns=['target']), train["target"])

In [11]:
test.drop(columns=['target']).head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f91,f92,f93,f94,f95,f96,f97,f98,f99,f100
18,0.160589,-1.520287,-0.834185,-0.227720,1.006730,-0.596895,0.176150,-0.361009,-0.109023,-0.420028,...,1.392456,-0.410518,0.034375,-1.103184,0.612332,1.441942,2.927270,0.037542,-1.617801,-0.631437
42,0.646905,-0.119559,1.380139,0.510535,0.905718,1.021963,0.726512,1.752292,-0.339530,-1.167757,...,0.102541,2.585975,0.960932,1.515414,0.562854,0.581723,-2.202913,-0.103812,0.207489,0.126313
36,0.966917,1.601993,-1.417640,-0.461745,1.270529,-0.606963,-0.072347,0.587695,-1.358257,-0.551738,...,-0.470850,-1.309732,-0.092166,-0.860524,2.368335,-0.006334,0.250514,-0.778587,-0.215568,0.713026
76,0.695538,-0.650024,-0.924233,-1.846188,-1.449645,-0.005596,-0.617253,-0.183197,-1.091701,0.575205,...,-0.957151,-0.383971,-0.387100,-1.517874,0.683569,1.795211,-0.478837,0.207267,-0.359769,0.408653
53,-1.290561,0.566772,0.069370,-2.099356,-0.048965,0.447394,-0.375634,-1.153492,-0.448543,0.543391,...,0.887080,-1.027404,0.238555,1.534482,0.789920,1.325276,-0.739771,0.808036,1.378470,0.503090

In [12]:
data = train_scalar.transform(test.drop(columns=['target']))
data

array([[ 0.20624535, -1.66873215, -0.74793715, ...,  0.02231694,
        -1.48704545, -0.87948559],
       [ 0.70599611, -0.05929934,  1.45776038, ..., -0.1152248 ,
         0.23827522, -0.02563871],
       [ 1.03485014,  1.91875867, -1.32911911, ..., -0.77179946,
        -0.16161125,  0.63548127],
       ...,
       [ 1.16757081,  0.68347767, -0.86336437, ...,  0.10869494,
         0.69697728, -1.0719948 ],
       [ 0.19495021, -0.60131131,  0.29597386, ..., -0.83781674,
        -1.18815138, -1.44147742],
       [-1.14768556,  1.44682872, -1.79578298, ..., -0.868029  ,
         0.79899885,  0.60610597]])

In [13]:
model = Ridge(random_state=42)
model.fit(train_scaled, train["target"])

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=42, solver='auto', tol=0.001)

In [16]:
data = model.predict(data)

In [17]:
answer2 = round(mean_squared_error(data, test["target"]), 2)

In [18]:
print('mse 1: {0:.2f}\nmse 2: {1:.2f}'.format(answer1, answer2))

mse 1: 4921.83
mse 2: 4195.00